name: DockerHubUpdateDescription

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker-description.yml

env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_REPO }}/coredns

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_IMAGE }}