name: DockerBuildPush

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Information
        run: |
          echo "DockerHub Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DockerHub Repository: ${{ secrets.DOCKERHUB_REPO }}"

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_REPO }}/coredns
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker Tags and Labels
        run: |
          echo "Docker Tags: ${{ steps.meta.outputs.tags }}"
          echo "Docker Labels: ${{ steps.meta.outputs.labels }}"

